# Generated by Django 6.0.7 on 2026-07-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoprocess',
            options={'verbose_name': 'Video Process', 'verbose_name_plural': 'Video Processes'},
        ),
        migrations.AddField(
            model_name='videoprocess',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprocess',
            name='output_video',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
    ]
