# Generated by Django 6.0.7 on 2026-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_videoprocess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocess',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
    ]
