# Generated by Django 6.0.7 on 2026-07-14 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_videoprocess_person_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocess',
            name='nama_praktikum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoprocess',
            name='waktu_mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprocess',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('person_id', models.IntegerField()),
                ('activity', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='web.videoprocess')),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
            },
        ),
    ]
