# Generated by Django 6.0.7 on 2026-07-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_videoprocess_nama_praktikum_videoprocess_waktu_mulai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocess',
            name='fps',
            field=models.IntegerField(default=0),
        ),
    ]
